### ISSUE TITLE
Alt-Shift-L is captured by ChromeOS

### ISSUE THREAD

**Issue by zpencer** [WorldThirteen/youtube-watch-later-shortcut-ext#1]
This shortcut is captured by ChromeOS and it brings the search button into focus. After changing the key shortcut to something else, it works. I use Alt-L to add to playlist, Alt-K to remove.

**Comment by WorldThirteen** [comment]
Hi @zpencer, thank you for reporting this!
I'll schedule the default shortcut update for the following release with ensuring this will not harm existing users.
