### ISSUE TITLE
Pls give us the version for Mozilla Firefox!

### ISSUE THREAD

**Issue by rudavagyan** [WorldThirteen/youtube-watch-later-shortcut-ext#2]
I am trying to add it manually but it does not work!

**Comment by rudavagyan** [comment]
Thank you! Because I am considering to change my loved browser to have this feature) there is no alternative to this in firefox extensions!

**Comment by rudavagyan** [comment]
> Thank you for letting me know Mozilla Firefox users are interested in this! Can't give you any reliable estimate, but it's now in my nearest TODOs.

Thank you! Because I am considering to change my loved browser to have this feature) there is no alternative to this in firefox extensions!

**Comment by WorldThirteen** [comment]
@rudavagyan, Happy to notify that the extension was released for Firefox, you can check it out here: https://addons.mozilla.org/uk/firefox/addon/watch-later-shortcut-youtube.
