### ISSUE TITLE
Videos are not added to watch later 

### ISSUE THREAD

**Issue by rizerzero** [WorldThirteen/youtube-watch-later-shortcut-ext#5]
Hi,  
I'm on Mac Os Ventura, adding videos does not work and does not show any notifications, but removing shows a notification, and shows it even if the video is not in watch later, which is giving invalid information.

**Comment by WorldThirteen** [comment]
Hi @rizerzero!
Thank you for giving this a try. This extension provides a shorthand to the YouTube built-in capabilities, and showing the notification when a video is not in watch later play-list is a native YouTube behavior. I've encountered such behavior while removing video by hand when several tabs were out of sync.

As for the issue that the add video shortcut is not working for you, please check if you have no conflict key bindings by typing `chrome://extensions/shortcuts` at the URL for Chrome or `about:addons` for Firefox; the extension settings are expected to look like this:
<img width="704" alt="image" src="https://github.com/WorldThirteen/youtube-watch-later-shortcut-ext/assets/14346393/d1e2a890-454b-4cab-afb6-b82b55fd0c34">

If you have another extension/custom browser shortcut conflicted combination, you could update the "Add the current video from the Watch Later list." (oopsie, typo here `from->to`) to the combination that will be comfortable for you.

Please come back in case the issue does not in combination conflict with more details, like OS subversion, e.g. "13.5.2 (22G91)", browser version like: "Version 116.0.5845.187 (Official Build) (arm64)". This will help me identify and fix the issue for you and other users.

**Comment by rizerzero** [comment]
Thank you @WorldThirteen  for your quick response, I did not find any conflicts on Chrome, but maybe I have another shortcut at the OS level (I'm new to Mac OS). 
I changed the shortcut and it works now, so I looked again in the doc and saw that it's mentioned there that the shortcut can be changed via the Chrome settings which I did not see and I did not know that, I naturally clicked on the extension expecting to find options to change the shortcut.
My suggestion would be to have the message clearer on the doc or have a button on the app that brings the user to the page to change the shortcuts maybe...
Thank you!

**Comment by WorldThirteen** [comment]
I agree with you, and I will include related enhancements in the next release. There should not be any conflicting MacOS default shortcuts, but the world is moving, so maybe they added something. I will monitor via my experiments and other reports.

Thank you again. Closing this issue, but your suggestion will lead to an enhancement for all users soon.
