### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by purevertigo** [WorldThirteen/youtube-watch-later-shortcut-ext#8]
Doesn't seem to be working as of 25-1 -  windows

**Comment by WorldThirteen** [comment]
@purevertigo, Hi! Thank you for reaching out.
I will try to test it on Windows as soon as I am able to reach such a machine.

Have you recently updated Windows or Browser?
Do you use the Chrome or Firefox version of the extension?

**Comment by WorldThirteen** [comment]
@purevertigo,
I just double-checked on Windowsv11, and Chrome 121, and it worked fine.

This might happen due to some conflict in shortcut keys. In case you using Chrome, you can find it out at chrome://extensions/shortcuts

Could you please provide more details so I can help?

**Comment by purevertigo** [comment]
Sorry for late reply.

I checked the shortcuts section and in both my Mac and also my PC the extension failed to relay that shortcut into Chome.

**Comment by WorldThirteen** [comment]
@purevertigo, thank you for coming back to give additional info. Not sure I completely understand if you see the extension in ext-shortcut settings, are shortcuts empty, or filled (ALT+L) but don't work?

**Comment by WorldThirteen** [comment]
At the moment it lacks the details on how & why it is not working, there were no other reports for the same problem.
So I have to close the issue until further reports.

Feel free to reopen if you have more details on setup flow, shortcuts settings state, availability of conflicts with other extensions/shortcuts, etc.
